
project_id = "lnsyrmpucmllakuuiixe"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
api_port = 54325
smtp_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
public_bucket = "profile-pictures"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://lnsyrmpucmllakuuiixe.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[[auth.email.custom_smtp]]
enabled = false

[functions.auth-otp]
verify_jwt = false
