// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyttayztezkwwsejdfyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5dHRheXp0ZXprd3dzZWpkZnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDg3MDYsImV4cCI6MjA2ODg4NDcwNn0.CowJJP-g7zmlIU37B9nR8nETRvj_3AAizYRpRYX0SJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});