// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqegyglhlcypmzxwhcun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxZWd5Z2xobGN5cG16eHdoY3VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjM0NzgsImV4cCI6MjA2ODgzOTQ3OH0.u859rgkTTsnt5jrwkBk76_21dzyBfFfo7o5THi6vrZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});